heat_template_version: 2014-10-16

description: A template to deploy a load balanced web server

parameters:
  image:
    type: string
    description: Image utilisee pour les serveurs
    default: INF4410-Ubuntu-trusty-mini

  flavor:
    type: string
    description: Flavor utilisee par les serveurs
    default: INF4410-mini

  subnet_id:
    type: string
    description: Sous-reseau dans lequel le load balancer sera situe
    default: #A completer
    
  server_net_id:
    type: string
    label: Réseau interne
    description: Reseau ou sera situe l'instance
    default: cac571ab-8e5c-4332-8e05-4c69a56bda9e

    
    
resources:
  web_nodes:
      type: OS::Heat::ResourceGroup
      properties:
        count: 2
        resource_def: 
            type: OS::Nova::Server
            properties:
                name: web_node_%index%
                image: { get_param: image }
                flavor: { get_param: flavor }
                network: { get_param: server_net_id }
                user_data: | 
                    #!/bin/bash
                    wget http://secretaire.dorsal.polymtl.ca/~hdaoud/infonuagique/server.py
                    python server.py &


  pool:
    type: OS::Neutron::Pool
    properties:
      protocol: HTTP
      monitors: [{get_resource: monitor}]
      subnet_id: {get_param: subnet_id}
      lb_method: ROUND_ROBIN
      vip:
        protocol_port: 80

  lbalancer:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: 80
      pool_id: {get_resource: pool}

  lb_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: external_network_id}
      port_id: {get_attr: [pool, vip, port_id]}
        
  monitor:
      type: OS::Neutron::HealthMonitor
      properties:
        type: TCP
        delay: 13
        max_retries: 2
        timeout: 9

outputs:
  pool_ip_address:
    value: {get_attr: [pool, vip, address]}
    description: The IP address of the load balancing pool