heat_template_version: 2014-10-16

description: Un template pour demarrer un serveur web (1.2)

parameters:
  key_name:
    type: string
    label: Cle SSH
    description: Nom de la cle SSH utilisee pour communiquer avec le serveur
    constraints:
      - custom_constraint: nova.keypair
  image:
    type: string
    label: Image
    description: Image utilisee pour les serveurs
    default: INF4410-Ubuntu-trusty-mini

  flavor:
    type: string
    label: Flavor
    description: Flavor utilisee par les serveurs
    default: INF4410-mini
  
  public_net_id:
    type: string
    label: Réseau public
    description: Identifiant du reseau public pour lequel l'IP flottant sera alloue
    default: 0c3b1354-d3d5-4fec-86d3-19d4d1f13785
  
  private_net_id:
    type: string
    label: Réseau interne
    description: Reseau ou sera situe l'instance
    default: cac571ab-8e5c-4332-8e05-4c69a56bda9e

resources:
  webserver_port: 
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      
  webserver:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: 
        - port: { get_resource: webserver_port }
      user_data: | 
        #!/bin/bash
        wget https://raw.githubusercontent.com/felpel/INF4410-H16/master/TP3/srv/server-install.sh -O /tmp/server-install.sh
        chmod u+x /tmp/server-install.sh
        /tmp/server-install.sh
  
  webserver_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      port_id: { get_resource: webserver_port }
      floating_network_id: { get_param : public_net_id }
   
outputs:
  server_networks:
    description: Les reseaux du serveur deploye
    value: { get_attr: [webserver, networks] }   
  
  server_public_ip:
    description: L'adresse IP flottante du serveur sur le reseau public
    value: { get_attr: [ webserver_floating_ip, floating_ip_address ] }