#!/bin/bash

pushd $(dirname $0) > /dev/null
basepath=$(pwd)
popd > /dev/null

clear

java \
	-cp "$basepath"/deploy/dstr/distributor.jar:"$basepath"/lib/gson-2.6.2.jar:"$basepath"/deploy/shared/shared.jar \
	-Djava.security.policy="$basepath"/policy distributor.Client $*
